---
# Webserver role metadata with dependency on common role
galaxy_info:
  role_name: webserver
  author: rustible
  description: Nginx webserver configuration and management
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

# Role dependencies - common role is executed before webserver tasks
dependencies:
  - common
